name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on repository code
        uses: actions/checkout@v3
      - name: printing contents of hello_world.txt
        run: cat hello_world.txt
  
